apiVersion: apps/v1
kind: Deployment
metadata:
  name: perper-fabric
spec:
  selector:
    matchLabels:
      app: perper-fabric
  template:
    metadata:
      labels:
        app: perper-fabric
    spec:
      containers:
      - name: perper-fabric
        image: {{$.Params.perperImage}}
        command: ['perper-fabric/bin/perper-fabric', '-d', 'perper-fabric/config/example.xml']
        ports:
            - containerPort: 10800
            - containerPort: 40400
---
apiVersion: v1
kind: Service
metadata:
  name: perper-fabric
  labels:
    app: perper-fabric
spec:
  ports:
  - port: 10800
    protocol: TCP
    name: ignite
  - port: 40400
    protocol: TCP
    name: grpc
  selector:
    app: perper-fabric
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perper-scaler
spec:
  selector:
    matchLabels:
      app: perper-scaler
  template:
    metadata:
      labels:
        app: perper-scaler
    spec:
      containers:
      - name: perper-scaler
        image: {{$.Params.perperScalerImage}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perper-scaler-role
rules:
  - apiGroups: ["kudo.dev"]
    resources: ["instances"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perper-scaler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perper-scaler-role
subjects:
  - kind: ServiceAccount
    name: default