apiVersion: kudo.dev/v1beta1
appVersion: 0.8.0
kubernetesVersion: 0.16.0
kudoVersion: 0.19.0
maintainers:
- email: MyEmail@invalid
  name: My Name
name: perper-agent
operatorVersion: 0.1.5
plans:
  deploy:
    phases:
    - name: deploy
      steps:
      - name: deploy
        tasks:
        - deploy
      strategy: serial
    strategy: serial
tasks:
- kind: Apply
  name: deploy
  spec:
    resources:
      - deployment-template.yaml
