apiVersion: kudo.dev/v1beta1
parameters:
  - name: agent
    required: true
  - name: image
    required: true
  - name: instances
    default: []
    type: array
  - name: env
    default: {}
    type: map
  - name: singleInstance
    default: true
    type: boolean
