apiVersion: kudo.dev/v1beta1
parameters:
  - name: agent
    required: true
  - name: image
    required: true
  - name: command
    default: []
    type: array
  - name: instances
    default: []
    type: array
  - name: origInstances
    default: []
    type: array
  - name: env
    default: []
    type: array
