# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import fabric_pb2 as fabric__pb2


class FabricStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notifications = channel.unary_stream(
                '/perper.Fabric/Notifications',
                request_serializer=fabric__pb2.NotificationFilter.SerializeToString,
                response_deserializer=fabric__pb2.Notification.FromString,
                )
        self.CallResultNotification = channel.unary_unary(
                '/perper.Fabric/CallResultNotification',
                request_serializer=fabric__pb2.CallNotificationFilter.SerializeToString,
                response_deserializer=fabric__pb2.Notification.FromString,
                )


class FabricServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Notifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallResultNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FabricServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notifications': grpc.unary_stream_rpc_method_handler(
                    servicer.Notifications,
                    request_deserializer=fabric__pb2.NotificationFilter.FromString,
                    response_serializer=fabric__pb2.Notification.SerializeToString,
            ),
            'CallResultNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CallResultNotification,
                    request_deserializer=fabric__pb2.CallNotificationFilter.FromString,
                    response_serializer=fabric__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'perper.Fabric', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fabric(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Notifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/perper.Fabric/Notifications',
            fabric__pb2.NotificationFilter.SerializeToString,
            fabric__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallResultNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/perper.Fabric/CallResultNotification',
            fabric__pb2.CallNotificationFilter.SerializeToString,
            fabric__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
