using System;
using System.Threading;
using System.Threading.Tasks;
using Apache.Ignite.Core;
using Perper.Fabric.Streams;
using Perper.Protocol.Header;

namespace Perper.Fabric
{
    public static class Program
    {
        public static async Task Main(string[] args)
        {
            var ignite = Ignition.Start(new IgniteConfiguration
            {
                IgniteHome = "/usr/share/apache-ignite"
            });

            var cancellationTokenSource = new CancellationTokenSource();
            AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) => cancellationTokenSource.Cancel();

            var launcherStreamHeader = new StreamHeader("Launcher", StreamKind.Sink);
            var launcherStreamObject = ignite.GetBinary().GetBuilder(launcherStreamHeader.ToString()).Build();
            var launcherStream = new Stream(launcherStreamHeader, launcherStreamObject, ignite);
            await foreach (var unused in launcherStream.Listen(cancellationTokenSource.Token))
            {
                throw new Exception("Unexpected data generated by the Launcher stream.");
            }
        }
    }
}