using System;
using System.Threading;
using System.Threading.Tasks;
using Apache.Ignite.Core;
using Apache.Ignite.Core.Binary;
using Ignite.Extensions;
using Perper.Fabric.Streams;

namespace Perper.Fabric
{
    public static class Program
    {
        public static async Task Main(string[] args)
        {
            var ignite = Ignition.Start(new IgniteConfiguration
            {
                IgniteHome = "/usr/share/apache-ignite"
            });
            
            var cancellationTokenSource = new CancellationTokenSource();
            AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) => cancellationTokenSource.Cancel();

            var launcherCacheObject = ignite.GetBinary().GetCacheObjectBuilder("Launcher").Build();
            var launcherStream = new Stream("Launcher", default, launcherCacheObject, ignite);
            await foreach (var unused in launcherStream.Listen(cancellationTokenSource.Token))
            {
                throw new Exception("Unexpected data generated by the Launcher stream.");
            }
        }
    }
}