{% set name = "azure_functions_worker" %}
{% set version = "1.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dc9ea6dae05bd792edf3c93c73ed2237e08a605875b0620f454d9d13db39ad0b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - grpcio-tools~ 1.33.1
    - grpcio~ 1.33.1
    - pip
    - python
  run:
    - grpcio-tools~ 1.33.1
    - grpcio~ 1.33.1
    - python

test:
  imports:
    - azure_functions_worker
    - azure_functions_worker._thirdparty
    - azure_functions_worker.bindings
    - azure_functions_worker.protos
    - azure_functions_worker.protos.identity
    - azure_functions_worker.protos.shared
    - azure_functions_worker.utils

about:
  home: "https://github.com/Azure/azure-functions-python-worker"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Python Language Worker for Azure Functions Host"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
