[tool.poetry]
name = "ds-python"
version = "0.1.0"
description = ""
authors = ["Viktor Velev <viktorvelev8@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pyignite = "^0.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
