{{ range $index, $instance := $.Params.instances }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Name }}-{{ lower $instance }}
  labels:
    perper.obecto.com/agent: {{ $.Params.agent }}
    perper.obecto.com/instance: {{ $instance }}
spec:
  containers:
  - name: agent
    image: {{ $.Params.image }}
    command: {{ $.Params.command }}
    env:
    - name: X_PERPER_AGENT
      value: {{ $.Params.agent }}
    - name: X_PERPER_INSTANCE
      value: {{ index $.Params.origInstances $index }}
    - name: APACHE_IGNITE_ENDPOINT
      value: perper-fabric.{{ $.Params.fabricNamespace }}.svc.cluster.local:10800
    - name: PERPER_FABRIC_ENDPOINT
      value: http://perper-fabric.{{ $.Params.fabricNamespace }}.svc.cluster.local:40400
    {{ range $envParam := $.Params.env }}
    - name: {{ $envParam.name }}
      value: {{ $envParam.value }}
    {{ end }}
  restartPolicy: Never
{{ end }}