# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fabric.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fabric.proto',
  package='perper',
  syntax='proto2',
  serialized_options=b'\n\032com.obecto.perper.protobufP\001\252\002\"Perper.WebJobs.Extensions.Protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x66\x61\x62ric.proto\x12\x06perper\"+\n\x12NotificationFilter\x12\x15\n\ragentDelegate\x18\x01 \x02(\t\"A\n\x16\x43\x61llNotificationFilter\x12\x15\n\ragentDelegate\x18\x01 \x02(\t\x12\x10\n\x08\x63\x61llName\x18\x02 \x02(\t\"d\n\x0cNotification\x12\x17\n\x0fnotificationKey\x18\x01 \x02(\x03\x12\x18\n\x0estringAffinity\x18\x02 \x01(\tH\x00\x12\x15\n\x0bintAffinity\x18\x03 \x01(\x03H\x00\x42\n\n\x08\x61\x66\x66inity2\xa1\x01\n\x06\x46\x61\x62ric\x12\x45\n\rNotifications\x12\x1a.perper.NotificationFilter\x1a\x14.perper.Notification\"\x00\x30\x01\x12P\n\x16\x43\x61llResultNotification\x12\x1e.perper.CallNotificationFilter\x1a\x14.perper.Notification\"\x00\x42\x43\n\x1a\x63om.obecto.perper.protobufP\x01\xaa\x02\"Perper.WebJobs.Extensions.Protobuf'
)




_NOTIFICATIONFILTER = _descriptor.Descriptor(
  name='NotificationFilter',
  full_name='perper.NotificationFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='agentDelegate', full_name='perper.NotificationFilter.agentDelegate', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)


_CALLNOTIFICATIONFILTER = _descriptor.Descriptor(
  name='CallNotificationFilter',
  full_name='perper.CallNotificationFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='agentDelegate', full_name='perper.CallNotificationFilter.agentDelegate', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callName', full_name='perper.CallNotificationFilter.callName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=134,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='perper.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notificationKey', full_name='perper.Notification.notificationKey', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stringAffinity', full_name='perper.Notification.stringAffinity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intAffinity', full_name='perper.Notification.intAffinity', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='affinity', full_name='perper.Notification.affinity',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=136,
  serialized_end=236,
)

_NOTIFICATION.oneofs_by_name['affinity'].fields.append(
  _NOTIFICATION.fields_by_name['stringAffinity'])
_NOTIFICATION.fields_by_name['stringAffinity'].containing_oneof = _NOTIFICATION.oneofs_by_name['affinity']
_NOTIFICATION.oneofs_by_name['affinity'].fields.append(
  _NOTIFICATION.fields_by_name['intAffinity'])
_NOTIFICATION.fields_by_name['intAffinity'].containing_oneof = _NOTIFICATION.oneofs_by_name['affinity']
DESCRIPTOR.message_types_by_name['NotificationFilter'] = _NOTIFICATIONFILTER
DESCRIPTOR.message_types_by_name['CallNotificationFilter'] = _CALLNOTIFICATIONFILTER
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationFilter = _reflection.GeneratedProtocolMessageType('NotificationFilter', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONFILTER,
  '__module__' : 'fabric_pb2'
  # @@protoc_insertion_point(class_scope:perper.NotificationFilter)
  })
_sym_db.RegisterMessage(NotificationFilter)

CallNotificationFilter = _reflection.GeneratedProtocolMessageType('CallNotificationFilter', (_message.Message,), {
  'DESCRIPTOR' : _CALLNOTIFICATIONFILTER,
  '__module__' : 'fabric_pb2'
  # @@protoc_insertion_point(class_scope:perper.CallNotificationFilter)
  })
_sym_db.RegisterMessage(CallNotificationFilter)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'fabric_pb2'
  # @@protoc_insertion_point(class_scope:perper.Notification)
  })
_sym_db.RegisterMessage(Notification)


DESCRIPTOR._options = None

_FABRIC = _descriptor.ServiceDescriptor(
  name='Fabric',
  full_name='perper.Fabric',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=239,
  serialized_end=400,
  methods=[
  _descriptor.MethodDescriptor(
    name='Notifications',
    full_name='perper.Fabric.Notifications',
    index=0,
    containing_service=None,
    input_type=_NOTIFICATIONFILTER,
    output_type=_NOTIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CallResultNotification',
    full_name='perper.Fabric.CallResultNotification',
    index=1,
    containing_service=None,
    input_type=_CALLNOTIFICATIONFILTER,
    output_type=_NOTIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FABRIC)

DESCRIPTOR.services_by_name['Fabric'] = _FABRIC

# @@protoc_insertion_point(module_scope)
