name: .NET Checks

on:
  push:
    paths:
      - 'agent/dotnet/**'
      - 'samples/dotnet/**'

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - run: dotnet tool install --global dotnet-format --version 5.0

      - uses: actions/checkout@v1

      - name: Build dotnet
        run: dotnet build

      - name: Format dotnet
        run: dotnet format --verify-no-changes
