name: Release .NET Agent

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['5.0.x', '6.0.x']

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build with dotnet
        working-directory: ./agent/dotnet/src/Perper
        run: dotnet build --configuration Release

      - name: Push generated package to nuget.org
        working-directory: ./agent/dotnet/src/Perper/bin/Release
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
